name: Deploy to Vercel

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs (Only Latest Commit Deploys)
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}  # Kept default token

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Link Vercel Project
        run: vercel link --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Production (Main Branch)
        if: github.ref == 'refs/heads/main'
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Preview (Other Branches)
        if: github.ref != 'refs/heads/main'
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
